const flightDetails = [
  {
    id: 1,
    pid: 1,
    planesList: [
      {
        id: 1,
        from: "Chennai",
        to: "Colombo",
        depart: "10:00",
        arrive: "11:25",
        airline: "JetBlue Airways",
        totalHrs: "1h 25m",
        price: "14,369",
      },
      {
        id: 2,
        from: "Chennai",
        to: "Colombo",
        depart: "01:00",
        arrive: "02:30",
        airline: "IndiGo",
        totalHrs: "1h 30m",
        price: "14,737",
      },
      {
        id: 3,
        from: "Chennai",
        to: "Colombo",
        depart: "03:10",
        arrive: "04:35",
        airline: "Delta Air Lines",
        totalHrs: "1h 20m",
        price: "14,558",
      },
    ],
  },
  {
    id: 2,
    pid: 2,
    planesList: [
      {
        id: 1,
        from: "Kolkata",
        to: "Thailand",
        depart: "00:30",
        arrive: "04:30",
        airline: "JetBlue Airways",
        totalHrs: "2h 30m",
        price: "12,424",
      },
      {
        id: 2,
        from: "Kolkata",
        to: "Thailand",
        depart: "03:10",
        arrive: "04:35",
        airline: "IndiGo",
        totalHrs: "2h 30m",
        price: "13,037",
      },
      {
        id: 3,
        from: "Kolkata",
        to: "Thailand",
        depart: "01:00",
        arrive: "02:30",
        airline: "Delta Air Lines",
        totalHrs: "2h 30m",
        price: "12,520",
      },
    ],
  },
  {
    id: 3,
    pid: 3,
    planesList: [
      {
        id: 1,
        from: "Delhi",
        to: "Kathmandu",
        depart: "11:10",
        arrive: "13:05",
        airline: "JetBlue Airways",
        totalHrs: "1h 40m",
        price: "11,193",
      },
      {
        id: 2,
        from: "Delhi",
        to: "Kathmandu",
        depart: "07:00",
        arrive: "09:05",
        airline: "IndiGo",
        totalHrs: "1h 50m",
        price: "11,372",
      },
      {
        id: 3,
        from: "Delhi",
        to: "Kathmandu",
        depart: "12:55",
        arrive: "14:45",
        airline: "Delta Air Lines",
        totalHrs: "1h 45m",
        price: "11,747",
      },
    ],
  },
  {
    id: 4,
    pid: 4,
    planesList: [
      {
        id: 1,
        from: "Kolkata",
        to: "Bangladesh",
        depart: "11:30",
        arrive: "13:00",
        airline: "JetBlue Airways",
        totalHrs: "1h 00m",
        price: "10,011",
      },
      {
        id: 2,
        from: "Kolkata",
        to: "Bangladesh",
        depart: "14:05",
        arrive: "15:35",
        airline: "IndiGo",
        totalHrs: "1h 00m",
        price: "11,309",
      },
      {
        id: 3,
        from: "Kolkata",
        to: "Bangladesh",
        depart: "08:45",
        arrive: "10:10",
        airline: "Delta Air Lines",
        totalHrs: "0h 55m",
        price: "10,544",
      },
    ],
  },
  {
    id: 5,
    pid: 5,
    planesList: [
      {
        id: 1,
        from: "Mumbai",
        to: "Maldives",
        depart: "09:30",
        arrive: "11:45",
        airline: "JetBlue Airways",
        totalHrs: "2h 45m",
        price: "18,366",
      },
      {
        id: 2,
        from: "Mumbai",
        to: "Maldives",
        depart: "10:40",
        arrive: "13:00",
        airline: "IndiGo",
        totalHrs: "2h 50m",
        price: "16,879",
      },
      {
        id: 3,
        from: "Mumbai",
        to: "Maldives",
        depart: "01:30",
        arrive: "03:45",
        airline: "Delta Air Lines",
        totalHrs: "2h 45m",
        price: "12,520",
      },
    ],
  },
  {
    id: 6,
    pid: 6,
    planesList: [
      {
        id: 1,
        from: "Thiruvananthapuram",
        to: "Singapore",
        depart: "23:25",
        arrive: "06:40",
        airline: "JetBlue Airways",
        totalHrs: "4h 45m",
        price: "13,828",
      },
      {
        id: 2,
        from: "Thiruvananthapuram",
        to: "Singapore",
        depart: "22:25",
        arrive: "05:40",
        airline: "IndiGo",
        totalHrs: "2h 30m",
        price: "13,037",
      },
      {
        id: 3,
        from: "Thiruvananthapuram",
        to: "Singapore",
        depart: "21:25",
        arrive: "04:40",
        airline: "Delta Air Lines",
        totalHrs: "2h 30m",
        price: "13,520",
      },
    ],
  },
];

export default flightDetails;
